# Basic
title: 李涛涛的博客
subtitle: 
welcome_message: <a href="http://ltt-gddxz.github.io" target="_blank"></a>
description: 关注机器学习和图像处理，也记录个人生活与思考。
creator: <a href="http://weibo.com/u/2720974317?refer_flag=1001030201_">@李涛涛Thinking</a>
creator: <a href="http://ltt-gddxz.github.io">@ltt-gddxz</a>

url: "http://ltt-gddxz.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: black

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 关于, description: personal information, url: 'http://ltt-gddxz.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 李涛涛Thinking
    github: ltt-gddxz
    mail: 18810271756@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
