# Basic
title: 李涛涛
subtitle: 一个书写的地方
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
# description: Vno Jekyll is a port of my Ghost theme vno.
# creator: <a href="http://onev.cat">@onevcat</a>

url: "http://ltt-gddxz.github.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: black

# The blog button should not be removed.
blog_button:
    title: 文章
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 关于我, description: about, url: 'http://ltt-gddxz.github.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: ltt-gddxz
    # duoshuo: 
    
# Social
social:
    weibo: http://ltt-gddxz.github.com
    github: onevcat
#    twitter: onevcat
#    gplus: 107108267983477358170
    mail: ltt798253982@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
